# Generated by Django 4.0.5 on 2022-06-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cientificas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, upload_to='fotos')),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
