# Generated by Django 4.0.5 on 2022-06-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cientificas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cientificas',
            new_name='Cientifica',
        ),
    ]
